behaviors:
  BoatAgent:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 50000

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      num_epoch: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
